# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keystork.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekeystork.proto\x12\x0bkeystork.v1\"\xc6\x01\n\x05\x45rror\x12%\n\x04kind\x18\x01 \x01(\x0e\x32\x17.keystork.v1.Error.Kind\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x16\n\x0e\x65xception_code\x18\x04 \x01(\x05\"_\n\x04Kind\x12\x14\n\x10KIND_UNSPECIFIED\x10\x00\x12\x14\n\x10SERVICE_SPECIFIC\x10\x01\x12\x0f\n\x0bTRANSACTION\x10\x02\x12\x0c\n\x08PROTOCOL\x10\x03\x12\x0c\n\x08IDENTITY\x10\x04\"2\n\tHandshake\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x0b\n\x03uid\x18\x02 \x01(\r\"o\n\x0cHandshakeAck\x12!\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x12.keystork.v1.Error\x12\x18\n\x10protocol_version\x18\x02 \x01(\r\x12\"\n\x1akeystore_interface_version\x18\x03 \x01(\x05\"i\n\rKeyDescriptor\x12\x0e\n\x06\x64omain\x18\x01 \x01(\x05\x12\x0e\n\x06nspace\x18\x02 \x01(\x03\x12\x12\n\x05\x61lias\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x62lob\x18\x04 \x01(\x0cH\x01\x88\x01\x01\x42\x08\n\x06_aliasB\x07\n\x05_blob\"x\n\x0bListRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\x05\x12\x0e\n\x06nspace\x18\x02 \x01(\x03\x12\x0f\n\x07\x62\x61tched\x18\x03 \x01(\x08\x12 \n\x13starting_past_alias\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x16\n\x14_starting_past_alias\";\n\x0cListResponse\x12+\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1a.keystork.v1.KeyDescriptor\";\n\x07Request\x12(\n\x04list\x18\x01 \x01(\x0b\x32\x18.keystork.v1.ListRequestH\x00\x42\x06\n\x04\x62ody\"b\n\x08Response\x12#\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x12.keystork.v1.ErrorH\x00\x12)\n\x04list\x18\x02 \x01(\x0b\x32\x19.keystork.v1.ListResponseH\x00\x42\x06\n\x04\x62ody*K\n\x0fProtocolVersion\x12 \n\x1cPROTOCOL_VERSION_UNSPECIFIED\x10\x00\x12\x16\n\x12PROTOCOL_VERSION_1\x10\x01\x42\x02H\x03\x62\x06proto3')

_PROTOCOLVERSION = DESCRIPTOR.enum_types_by_name['ProtocolVersion']
ProtocolVersion = enum_type_wrapper.EnumTypeWrapper(_PROTOCOLVERSION)
PROTOCOL_VERSION_UNSPECIFIED = 0
PROTOCOL_VERSION_1 = 1


_ERROR = DESCRIPTOR.message_types_by_name['Error']
_HANDSHAKE = DESCRIPTOR.message_types_by_name['Handshake']
_HANDSHAKEACK = DESCRIPTOR.message_types_by_name['HandshakeAck']
_KEYDESCRIPTOR = DESCRIPTOR.message_types_by_name['KeyDescriptor']
_LISTREQUEST = DESCRIPTOR.message_types_by_name['ListRequest']
_LISTRESPONSE = DESCRIPTOR.message_types_by_name['ListResponse']
_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_ERROR_KIND = _ERROR.enum_types_by_name['Kind']
Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.Error)
  })
_sym_db.RegisterMessage(Error)

Handshake = _reflection.GeneratedProtocolMessageType('Handshake', (_message.Message,), {
  'DESCRIPTOR' : _HANDSHAKE,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.Handshake)
  })
_sym_db.RegisterMessage(Handshake)

HandshakeAck = _reflection.GeneratedProtocolMessageType('HandshakeAck', (_message.Message,), {
  'DESCRIPTOR' : _HANDSHAKEACK,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.HandshakeAck)
  })
_sym_db.RegisterMessage(HandshakeAck)

KeyDescriptor = _reflection.GeneratedProtocolMessageType('KeyDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _KEYDESCRIPTOR,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.KeyDescriptor)
  })
_sym_db.RegisterMessage(KeyDescriptor)

ListRequest = _reflection.GeneratedProtocolMessageType('ListRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQUEST,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.ListRequest)
  })
_sym_db.RegisterMessage(ListRequest)

ListResponse = _reflection.GeneratedProtocolMessageType('ListResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTRESPONSE,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.ListResponse)
  })
_sym_db.RegisterMessage(ListResponse)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'keystork_pb2'
  # @@protoc_insertion_point(class_scope:keystork.v1.Response)
  })
_sym_db.RegisterMessage(Response)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _PROTOCOLVERSION._serialized_start=848
  _PROTOCOLVERSION._serialized_end=923
  _ERROR._serialized_start=32
  _ERROR._serialized_end=230
  _ERROR_KIND._serialized_start=135
  _ERROR_KIND._serialized_end=230
  _HANDSHAKE._serialized_start=232
  _HANDSHAKE._serialized_end=282
  _HANDSHAKEACK._serialized_start=284
  _HANDSHAKEACK._serialized_end=395
  _KEYDESCRIPTOR._serialized_start=397
  _KEYDESCRIPTOR._serialized_end=502
  _LISTREQUEST._serialized_start=504
  _LISTREQUEST._serialized_end=624
  _LISTRESPONSE._serialized_start=626
  _LISTRESPONSE._serialized_end=685
  _REQUEST._serialized_start=687
  _REQUEST._serialized_end=746
  _RESPONSE._serialized_start=748
  _RESPONSE._serialized_end=846
# @@protoc_insertion_point(module_scope)
