# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spatula.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rspatula.proto\x12\x0fgmscore.spatula\"\x95\x01\n\tDeviceKey\x12\x12\n\x05keyId\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x15\n\x08\x64\x65viceId\x18\x03 \x01(\x04H\x01\x88\x01\x01\x12\x16\n\tmacSecret\x18\x04 \x01(\x0cH\x02\x88\x01\x01\x12\x14\n\x07keyCert\x18\x05 \x01(\x0cH\x03\x88\x01\x01\x42\x08\n\x06_keyIdB\x0b\n\t_deviceIdB\x0c\n\n_macSecretB\n\n\x08_keyCert\"\xe8\x02\n\x12SpatulaHeaderProto\x12I\n\x0bpackageInfo\x18\x01 \x01(\x0b\x32/.gmscore.spatula.SpatulaHeaderProto.PackageInfoH\x00\x88\x01\x01\x12\x11\n\x04hmac\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x15\n\x08\x64\x65viceId\x18\x03 \x01(\x04H\x02\x88\x01\x01\x12\x12\n\x05keyId\x18\x04 \x01(\x04H\x03\x88\x01\x01\x12\x14\n\x07keyCert\x18\x05 \x01(\x0cH\x04\x88\x01\x01\x1aw\n\x0bPackageInfo\x12\x18\n\x0bpackageName\x18\x01 \x01(\tH\x00\x88\x01\x01\x12#\n\x16packageCertificateHash\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_packageNameB\x19\n\x17_packageCertificateHashB\x0e\n\x0c_packageInfoB\x07\n\x05_hmacB\x0b\n\t_deviceIdB\x08\n\x06_keyIdB\n\n\x08_keyCertb\x06proto3')



_DEVICEKEY = DESCRIPTOR.message_types_by_name['DeviceKey']
_SPATULAHEADERPROTO = DESCRIPTOR.message_types_by_name['SpatulaHeaderProto']
_SPATULAHEADERPROTO_PACKAGEINFO = _SPATULAHEADERPROTO.nested_types_by_name['PackageInfo']
DeviceKey = _reflection.GeneratedProtocolMessageType('DeviceKey', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEKEY,
  '__module__' : 'spatula_pb2'
  # @@protoc_insertion_point(class_scope:gmscore.spatula.DeviceKey)
  })
_sym_db.RegisterMessage(DeviceKey)

SpatulaHeaderProto = _reflection.GeneratedProtocolMessageType('SpatulaHeaderProto', (_message.Message,), {

  'PackageInfo' : _reflection.GeneratedProtocolMessageType('PackageInfo', (_message.Message,), {
    'DESCRIPTOR' : _SPATULAHEADERPROTO_PACKAGEINFO,
    '__module__' : 'spatula_pb2'
    # @@protoc_insertion_point(class_scope:gmscore.spatula.SpatulaHeaderProto.PackageInfo)
    })
  ,
  'DESCRIPTOR' : _SPATULAHEADERPROTO,
  '__module__' : 'spatula_pb2'
  # @@protoc_insertion_point(class_scope:gmscore.spatula.SpatulaHeaderProto)
  })
_sym_db.RegisterMessage(SpatulaHeaderProto)
_sym_db.RegisterMessage(SpatulaHeaderProto.PackageInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DEVICEKEY._serialized_start=35
  _DEVICEKEY._serialized_end=184
  _SPATULAHEADERPROTO._serialized_start=187
  _SPATULAHEADERPROTO._serialized_end=547
  _SPATULAHEADERPROTO_PACKAGEINFO._serialized_start=368
  _SPATULAHEADERPROTO_PACKAGEINFO._serialized_end=487
# @@protoc_insertion_point(module_scope)
