import com.google.protobuf.gradle.proto

// The agent's Java half, built as an ordinary Android app.
//
// It is never installed. What is wanted is the dex: an app build is simply the
// supported way to get a dependency like the Play Integrity SDK compiled and
// dexed together with our own classes, transitive dependencies and all. CMake
// extracts classes.dex from the APK and embeds it in the agent, which is
// embedded in the daemon.
//
// Consequences of being a dex and not an app, both load-bearing:
//
//   *Resources are lost.* Only the dex is taken, so anything here that reads
//   its own R.* would fail. The resources the process does have are the target
//   app's, which are untouched.
//
//   *The manifest is lost too.* It is declared below to say what the classes
//   are for, and because a future minified build would need it as the root of
//   the keep graph, but at runtime the framework is told about these classes
//   by the agent rewriting the bind data, not by any manifest.

// Must match the protoc the daemon's CMake and scripts/gen_proto.sh use: a
// generator and a runtime from different series fail deep inside generated
// code with an unreadable message. 3.19 is the last series with no abseil
// dependency, which is what keeps the daemon's static link small.
val PROTOBUF_VERSION = "3.19.6"

plugins {
    id("com.android.application") version "8.13.2"
    // Generates the wire protocol's Java here rather than committing it. The
    // C++ is generated by the daemon's CMake for the same reason: lite code
    // and the runtime it links against must be the same version, and pinning
    // both in one file is the only way that stays true. The Python is the
    // exception, and is committed so the client installs without a protoc.
    id("com.google.protobuf") version "0.9.4"
}

android {
    namespace = "keystork"
    compileSdk = 36

    sourceSets {
        getByName("main") {
            // The one normative copy, at the top of the repository.
            proto { srcDir("${rootDir}/../../../proto") }
        }
    }

    defaultConfig {
        applicationId = "keystork.agent"
        // The daemon's own floor is API 31; there is no reason for this to be
        // lower, and a higher minSdk keeps d8 from desugaring what the device
        // can already do.
        minSdk = 31
        targetSdk = 36
    }

    buildTypes {
        release {
            // Shrinking earns its place here for an unusual reason: this dex
            // is written into somebody else's process, so what it carries is
            // resident in every injected app. Most of the generated protocol
            // is messages the app never sees -- keystore, exec -- and most of
            // the Play SDK is unreachable from one token call.
            //
            // R8 normally roots its keep graph in the manifest, which is
            // meaningless here because nothing installs this APK, so the roots
            // are stated outright in proguard-rules.pro instead.
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"),
                          "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

protobuf {
    protoc { artifact = "com.google.protobuf:protoc:$PROTOBUF_VERSION" }
    generateProtoTasks {
        all().forEach { task ->
            task.builtins {
                // maybeCreate, not named: on an Android project the plugin
                // registers no java builtin by default, so there is nothing to
                // look up until we ask for one.
                //
                // Lite, matching optimize_for in the .proto and the runtime
                // below. The full Java runtime is several times the size, and
                // this dex is written into somebody else's process.
                maybeCreate("java").option("lite")
            }
        }
    }
}

dependencies {
    implementation("com.google.android.play:integrity:1.6.0")

    // The wire protocol, generated from proto/keystork.proto by
    // scripts/gen_proto.sh and committed. Lite, and pinned to the same version
    // as the generator and as the daemon's own runtime -- a mismatch there
    // fails deep inside generated code with an unreadable message.
    implementation("com.google.protobuf:protobuf-javalite:$PROTOBUF_VERSION")
}
