# Emits an assembly stub that pulls a file into the .rodata of whatever links
# it, bracketed by <SYMBOL>Start and <SYMBOL>End.
#
# .incbin rather than a generated C array: the array form is a source file
# several times the size of the data, which the compiler then has to parse, for
# a result that is byte for byte the same. Run as a script step because the
# input is usually another target's output and only exists once it has built.
#
#   cmake -DBLOB=<file> -DSYMBOL=kThing -DOUTPUT=<file.S> -P embed_blob.cmake
#
# Used twice over: the dex is embedded in the agent, and the agent in the
# daemon. What lands on the device is still one file.

if(NOT DEFINED BLOB OR NOT DEFINED SYMBOL OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_blob.cmake needs -DBLOB, -DSYMBOL and -DOUTPUT")
endif()

file(WRITE "${OUTPUT}" "\
// Generated by cmake/embed_blob.cmake from ${BLOB}. Do not edit.
    .section .rodata
    .balign 16
    .globl ${SYMBOL}Start
${SYMBOL}Start:
    .incbin \"${BLOB}\"
    .globl ${SYMBOL}End
${SYMBOL}End:
")
