# Emits an assembly stub that pulls the built agent into keystorkd's .rodata.
#
# .incbin rather than a generated C array: the array form is a multi-megabyte
# source file that the compiler then has to parse, for a result that is byte
# for byte the same. Run as a script step because the agent's path is only
# known once its target has been built.
#
#   cmake -DAGENT=<path to the .so> -DOUTPUT=<path to the .S> -P embed_agent.cmake

if(NOT DEFINED AGENT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "embed_agent.cmake needs -DAGENT and -DOUTPUT")
endif()

file(WRITE "${OUTPUT}" "\
// Generated by cmake/embed_agent.cmake. Do not edit.
    .section .rodata
    .balign 16
    .globl kKeystorkAgentStart
kKeystorkAgentStart:
    .incbin \"${AGENT}\"
    .globl kKeystorkAgentEnd
kKeystorkAgentEnd:
")
