"""keystork -- drive a remote Android device's keystore2 over IP.

    >>> import keystork
    >>> with keystork.KeystoreSession(uid=10123) as ks:
    ...     for key in ks.list():
    ...         print(key)

The daemon on the device is deliberately dumb: it makes one keystore2 Binder
call as the session's UID and hands the raw bytes back. Everything that is
interpretation -- naming enum values, pagination, typed errors -- lives here.
"""

from .enums import (
    TAG_ENUMS,
    Algorithm,
    BinderException,
    BinderStatus,
    BlockMode,
    Digest,
    Domain,
    EcCurve,
    ErrorCode,
    HardwareAuthenticatorType,
    KeyOrigin,
    KeyPurpose,
    MlDsaVariant,
    PaddingMode,
    ResponseCode,
    SecurityLevel,
    Tag,
    TagType,
    name_of,
    type_of_tag,
)
from .errors import (
    ConnectionClosed,
    IdentityError,
    KeyMintError,
    KeystoreError,
    KeystorkError,
    ProtocolError,
    ServiceError,
    TransactionError,
    UnsupportedByDevice,
)
from .process import (
    CHUNK_BYTES,
    DEFAULT_WINDOW,
    ESCAPE,
    STDERR,
    STDOUT,
    ExitStatus,
    Process,
)
from .session import (
    DEFAULT_HOST,
    DEFAULT_PORT,
    DEFAULT_TIMEOUT,
    DEVICE_SHELL,
    MIN_INTERFACE_VERSION,
    PROTOCOL_VERSION,
    Authorization,
    Connection,
    Device,
    KeyDescriptor,
    KeyMetadata,
    KeyParameter,
    Operation,
    OperationBegun,
    OperationResult,
    NONCE_LENGTHS,
    KeystoreSession,
    PACKAGES_LIST,
    READ_CHUNK_BYTES,
    USER_OFFSET,
    kill_server,
    parse_packages_list,
    nonce_length,
    operation_parameters,
    run,
    system,
)

__version__ = "0.1.0"

__all__ = [
    "Algorithm",
    "Authorization",
    "BinderException",
    "BinderStatus",
    "BlockMode",
    "CHUNK_BYTES",
    "Connection",
    "ConnectionClosed",
    "DEFAULT_HOST",
    "DEFAULT_PORT",
    "DEFAULT_TIMEOUT",
    "DEFAULT_WINDOW",
    "DEVICE_SHELL",
    "Device",
    "Digest",
    "Domain",
    "ESCAPE",
    "EcCurve",
    "ErrorCode",
    "ExitStatus",
    "HardwareAuthenticatorType",
    "IdentityError",
    "KeyDescriptor",
    "KeyMetadata",
    "KeyMintError",
    "KeyOrigin",
    "KeyParameter",
    "KeyPurpose",
    "KeystoreError",
    "KeystoreSession",
    "KeystorkError",
    "MIN_INTERFACE_VERSION",
    "MlDsaVariant",
    "NONCE_LENGTHS",
    "Operation",
    "OperationBegun",
    "OperationResult",
    "PACKAGES_LIST",
    "PROTOCOL_VERSION",
    "PaddingMode",
    "Process",
    "ProtocolError",
    "READ_CHUNK_BYTES",
    "ResponseCode",
    "STDERR",
    "STDOUT",
    "SecurityLevel",
    "ServiceError",
    "TAG_ENUMS",
    "Tag",
    "TagType",
    "TransactionError",
    "USER_OFFSET",
    "UnsupportedByDevice",
    "kill_server",
    "name_of",
    "nonce_length",
    "operation_parameters",
    "parse_packages_list",
    "run",
    "system",
    "type_of_tag",
]
